#!/bin/sh

# List all installed hard drives
#
# Regexp from fai-disk-info
# https://github.com/faiproject/fai/blob/master/lib/fai-disk-info
#


lsblk -lo NAME,HOTPLUG -n \
    | awk '{if($2!=1){print $1}}' \
    | egrep 'etherd/e[[:digit:]]+\.[[:digit:]]+\b|i2o/hd.+\b|cciss/c[[:digit:]]+d[[:digit:]]+\b|ida/c[[:digit:]]+d[[:digit:]]+\b|rd/c[[:digit:]]+d[[:digit:]]+\b|fio.\b|hd.\b|sd[a-z]{1,2}\b|/disc\b|vd.\b|xvd.\b|nvme[[:digit:]]+n1$|mmcblk[[:digit:]]+$|md[0-9]{3,}$' \
    | sed 's,^,/dev/,'
