#!/usr/bin/env ansible-playbook

# Copyright © 2020 Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>

# Created: 2020-02-20
# Last changed: 2021-01-15 02:45:21

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.


# This ansible playbook bootstraps a new Debian like server.
#
# Invokation:
#
#    ./pb_bootstrap-ssh.yml -u user -l host -e password=debian
#
# Requirements:
#
#  * A Debian-like machine with network access (you can use a live-cd if you
#    want).
#  * A ssh access (Debian live-cd do not provide it) with root privileges
#    (sudo will do).
#  * The new server has to be declared within a 'install' group in the
#    inventory. To prevent from doing bad things do not forget to remove the
#    server from this group after setup completed.
#

- hosts: 'install'
  become_user: root
  become_method: sudo
  # Become is needed for this tasks
  become: '{{ become | default(True) }}'
  gather_facts: yes
  
  vars:
    ansible_ssh_pass: '{{ password | default(omit) }}'
    host_key_checking: '{{ host_key_checking | default(False) }}'
    system_install_ssh_chroot_pid: /run/ssh-chroot.pid

    ## Use a pre-generated installation
    #
    # If defined, download a tarball of a system install instead of using
    # debootstrap. This method is much more faster but requires an existing
    # image.
    #
    # This variable can be passed using the -e option or set in host
    # variables.
    #
    # system_install_base: []

  pre_tasks:
    - include_role:
        name: system-install
        tasks_from: stage-1/main

## Second stage
#
# This part is run within the remote chroot. Since Ansible is not able to
# daisy-chain connection, a ssh server has been started in the chroot and
# listens for connections on port 2222 by default.
#
# If any role has to be played, see the roles section below.
#
- hosts: 'install'
  user: 'root'
  become_user: root
  become_method: sudo
  # Become is needed for this tasks
  become: '{{ become | default(True) }}'
  gather_facts: yes

  vars:
    ansible_ssh_port: '{{ ssh_port | default(2222) }}'
    host_key_checking: '{{ host_key_checking | default(False) }}'
    ansible_python_interpreter: '{{ chroot_python_interpreter }}'


  tasks:
    - name: running stage 2
      include_role:
        name: system-install
        tasks_from: stage-2/main

## Third stage
#
# Cleanup the ssh server from the chroot and unmount all pseudo file
# systems.
#
- hosts: 'install'
  become_user: root
  become_method: sudo
  # Become is needed for this tasks
  become: '{{ become | default(True) }}'
  gather_facts: no

  vars:
    ansible_ssh_pass: '{{ password | default(omit) }}'
    host_key_checking: '{{ host_key_checking | default(False) }}'

  post_tasks:
    - include_role:
        name: system-install
        tasks_from: stage-3/main
    
