
## opensuse version and architechtures
#
# See http://download.opensuse.org/distribution/
system_install_opensuse_version: stable
system_install_opensuse_arch: x86_64

## Mirror to use
system_install_opensuse_mirror: 'http://download.opensuse.org'

## Base URLs for the repo file.
#
# name: is the repository name used by yum. It will be prefixed by
#       "bootstrap-" to easilly enable it with yum command.
# baseurl: the repository base URL.
# versions: versions to which this repository applies.
#
system_install_opensuse_repositories:
  # Base system
  - name: BaseOS
    repo: '{{ system_install_opensuse_mirror }}/distribution/{{ system_install_opensuse_version }}/repo/oss'
    versions:
      - stable
  # # Python
  # - name: AppStream
  #   baseurl: '{{ system_install_opensuse_mirror }}/opensuse/{{ system_install_opensuse_version }}/AppStream/{{ system_install_opensuse_arch }}/os/'
  #   versions:
  #     - 8

  # # Base system
  # - name: os
  #   baseurl: '{{ system_install_opensuse_mirror }}/opensuse/{{ system_install_opensuse_version }}/os/{{ system_install_opensuse_arch }}'
  #   versions:
  #     - 7

system_install_opensuse_packages:
  ### Centos
  - pkg: bash
  - pkg: yum
  - pkg: yum-utils
  - pkg: zypper
  - pkg: rpm
  - pkg: wget
  - pkg: sudo
  - pkg: kernel
  - pkg: xfsprogs
  - pkg: grub2-i386-pc
  - pkg: dhcp-client
  - pkg: openssh
  # Centos 7
  - pkg: python3


