## Linux vendor
#
# Can be either one of:
#   - debian
#   - ubuntu
#   - centos
#   - fedora
#   - opensuse
#   - alpine
#
system_install_vendor: ubuntu

## System archicteture
#
# Select archictecture. Use amd64 or change to a specific architecture if
# you know what you are doing.
#
system_install_arch: amd64


## Network interface for DHCP
system_install_network_iface: eth0

## Grub setup
#
# This will setup GRUB_CMDLINE_LINUX_DEFAULT.
#
# By default run in verbose mode and make sure traditional ethX names are
# used for network interfaces.
system_install_grub_linux_default:
  - verbose
  - 'net.ifnames=0'
  

## Root user credentials
#
# Deploy root credentials. Password is strongly dicouraged in favor of ssh
# key.
#
# system_install_root_ssh_keys is a list of ssh keys to deploy for root
# user.
#
# system_install_root_password is the root password. If not defined no
# password will be used for the root user preventing from loging (default).
#
# At least one method must be defined to process the 2nd stage of the system
# installation. The ssh keys method being the prefered one.
#
#system_install_root_password:
#
#system_install_root_ssh_keys:

  
## Disk to install the system to.
#
# The system will be installed on this hard drive. If not defined the first
# drive found by list-hard-drives will be used.
#
# BE CAREFUL ALL DATA ON THIS DRIVE WILL BE LOST!
#
# system_install_drive: /dev/vda


## Target mount 
#
# Path to mount the disk.
#
system_install_target: /srv

## Skip hard drive partition
#
# If set to true, all hardrive partitionning and formating will be skipped.
#
system_install_skip_partition: true


## Root file system
#
# xfs is the default file system but may not work on some old
# installation.
#
system_install_filesystem: xfs

## Partition scheme
#
# By default install the system in the whole disk. See ansible "parted"
# module and parted(1) manpage for further details.
#
# This setup works in most cases but YMMV.
system_install_partitions:
  - name: OS
    number: 1
    part_start: 4096s
    part_end: 100%
    flags:
      - boot
      - esp
    filesystem:
      force: yes
      fstype: '{{ system_install_filesystem }}'
      opts: -L SYSTEM
    mount:
      path: /
  - name: grub
    number: 2
    part_start: 2048s
    part_end: 4095s
    flags:
      - bios_grub
