---

- name: update initrd (Centos)
  shell:
    chroot '{{ system_install_target }}' dracut -fv --kver $(ls '{{ system_install_target }}/lib/modules' | head -n1)

- name: Copy grub configuration (Fedora)
  copy:
    src: etc/default/grub
    dest: '{{ system_install_target }}/etc/default/grub'
    mode: '0644'
      
- name: update grub (Fedora)
  command:
    chroot '{{ system_install_target }}' grub2-mkconfig -o /boot/grub2/grub.cfg

- name: Install grub (Fedora)
  command:
    chroot '{{ system_install_target }}' grub2-install '{{ item }}'
  with_items: '{{ system_install_drive }}'
