# Allows name resolving in the chroot environment. This is only required for
# operations in the chroot.
- name: ensure /run/resolvconf exists
  file:
    path: /run/resolvconf
    state: directory

- name: copy /etc/resolv.conf to /run/resolvconf
  copy:
    src: /etc/resolv.conf
    dest: /run/resolvconf
    remote_src: yes

# Some distos do not symlink /etc/resolv.conf to /run/resolvconf. Fix
# this to allow DNS resolution.
- name: copy /etc/resolv.conf to chroot
  copy:
    src: /etc/resolv.conf
    dest: '{{ system_install_target }}/etc/resolv.conf'
    remote_src: yes
  when: system_install_vendor in [ 'centos', 'arch' ]

