- name: Create required configuration files
  template:
    src: '{{ item.src }}'
    dest: '{{ system_install_target }}/{{ item.dest | default(item.src) }}'
  with_items:
    - src: etc/apk/repositories
    - src: etc/network/interfaces.alpine
      dest: etc/network/interfaces

