---

- name: Copy grub configuration (Centos)
  copy:
    src: etc/default/grub
    dest: '{{ system_install_target }}/etc/default/grub'
    mode: '0644'
      
- name: update grub (Centos)
  command:
    chroot '{{ system_install_target }}' grub2-mkconfig -o /boot/grub2/grub.cfg

- name: Install grub (Centos)
  command:
    chroot '{{ system_install_target }}' grub2-install '{{ system_install_drive }}'
