---

- include_tasks: grub-debian.yml
  when: system_install_vendor in [ 'debian', 'ubuntu' ]

- include_tasks: grub-centos.yml    
  when: system_install_vendor == 'centos'

- include_tasks: grub-fedora.yml
  when: system_install_vendor == 'fedora'

- include_tasks: grub-opensuse.yml    
  when: system_install_vendor == 'opensuse'

- include_tasks: grub-alpine.yml    
  when: system_install_vendor == 'alpine'

- include_tasks: grub-arch.yml
  when: system_install_vendor == 'arch'
