---

- name: install required packages
  apt:
    pkg:
      - parted
      - xfsprogs
    update_cache: yes
    install_recommends: no
    cache_valid_time: 3600

- name: copy list-hard-drives script
  copy:
    src: usr/local/sbin/list-hard-drives
    dest: /usr/local/sbin/list-hard-drives
    owner: root
    group: root
    mode: '0755'

- name: Find first hard drive
  block:
    
    - name: List all hard drives
      command:
        /usr/local/sbin/list-hard-drives
      register: _system_install_drives
        
    - name: set installer_drive
      set_fact:
        system_install_drive: '{{ _system_install_drives.stdout_lines[0] }}'
        
  when: system_install_drive is not defined

- name: Partition the hard drive
  block:
    
    - name: List partitions
      parted:
        device: '{{ system_install_drive }}'
      register: _system_install_partitions

    - name: umount pseudo file systems from the chroot target
      mount:
        path: '{{ system_install_target }}/{{ item.fs }}'
        state: unmounted
      with_items: '{{ system_install_pseudo_fs | reverse | list }}'

    # in case previous installation failed
    - name: unmount target partition
      mount:
        src: '{{ system_install_drive }}{{ item.number }}'
        path: '{{ system_install_target }}/{{ item.mount.path }}'
        fstype: '{{ item.filesystem.fstype }}'
        state: unmounted
      when:
        item.mount is defined
        and item.filesystem is defined
      with_items: '{{ system_install_partitions }}'

    - name: Remove all partitions
      parted:
        device: '{{ system_install_drive }}'
        number: '{{ item.num }}'
        state: absent
      with_items: '{{ _system_install_partitions.partitions }}'
    
    - name: Partition the hard drive
      parted:
        device: '{{ system_install_drive }}'
        label: '{{ item.label | default("gpt") }}'
        number: '{{ item.number }}'
        name: '{{ item.name }}'
        part_start: '{{ item.part_start }}'
        part_end: '{{ item.part_end }}'
        state: '{{ item.state | default("present") }}'
        flags: '{{ item.flags | default(omit) }}'
      with_items: '{{ system_install_partitions }}'

    - name: Format partitions
      filesystem:
        dev: '{{ system_install_drive }}{{ item.number }}'
        fstype: '{{ item.filesystem.fstype }}'
        opts: '{{ item.filesystem.opts | default(omit) }}'
        resizefs: '{{ item.filesystem.resizefs | default(False) }}'
        force: '{{ item.filesystem.force | default(False) }}'
      when: item.filesystem is defined
      with_items: '{{ system_install_partitions }}'
  when: not system_install_skip_partition
      
- name: mount target partition
  mount:
    src: '{{ system_install_drive }}{{ item.number }}'
    path: '{{ system_install_target }}/{{ item.mount.path }}'
    fstype: '{{ item.filesystem.fstype }}'
    state: mounted
  when:
    item.mount is defined
    and item.filesystem is defined
  with_items: '{{ system_install_partitions }}'
