---

- name: install required packages
  apt:
    pkg:
      - parted
      - xfsprogs
      - fai-setup-storage
      - patch
      - mdadm
      - cryptsetup
    update_cache: yes
    install_recommends: no
    cache_valid_time: 3600

- name: Patch setup-storage to get a list of boot devices
  patch:
    src: usr/sbin/setup-storage.patch
    dest: /usr/sbin/setup-storage
    strip: 0
    remote_src: False
      
- name: Partition the hard drive
  block:

    - name: umount pseudo file systems from the chroot target
      mount:
        path: '{{ system_install_target }}/{{ item.fs }}'
        state: unmounted
      with_items: '{{ system_install_pseudo_fs | reverse | list }}'

    # Find mounted patitions in case previous installation failed.
    - name: Find mounted partitions
      shell: |
         mount | awk '{print $3}' \
         | grep '^{{ system_install_target }}\($\|/\)' \
         | sort -r
      args:
        warn: false
      changed_when: false
      failed_when: false
      register: _system_install_mounted

    # Umount patitions in case previous installation failed.
    - name: umount file systems from the chroot target
      mount:
        path: '{{ item }}'
        state: unmounted
      with_items: '{{ (_system_install_mounted.stdout_lines | default([])) | list }}'

    - name: Copy setup-storage configuration file
      template:
        src: '{{ system_install_setup_storage_conf }}'
        dest: /tmp/setup-storage.conf
        validate: setup-storage -s -f %s
      
    ## In case of failure stop md / lvm etc... devices
    #
    #   mdadm --stop /dev/md0
    #
    - name: Create filesystems
      command:
        setup-storage -f /tmp/setup-storage.conf -X -y

  when: not system_install_skip_partition

- name: Mount partitions from the hard drive
  block:

    # TODO: handle case when setup-storage hasn't been run
    - name: retrieve data from setup-storage
      slurp:
        path: /tmp/fai/disk_var.yml
      register: _system_install_setup_storage

    # Read fstap and mount all partitions
    - name: read fstab
      shell: |-
        grep -v '^#' /tmp/fai/fstab | grep . \
        | awk '{print "  - { src:",$1,",path:",$2,",fstype:",$3,"}"}'
      register: _system_install_fstab
    
    - set_fact:
        system_install_drive: '{{ (_system_install_setup_storage.content | b64decode | from_yaml).PHYSICAL_BOOT_DEVICES }}'
        system_install_partitions: '{{ _system_install_fstab.stdout | from_yaml }}'
    
    - name: mount target partition
      mount:
        src: '{{ item.src }}'
        path: '{{ system_install_target }}/{{ item.path }}'
        fstype: '{{ item.fstype }}'
        state: mounted
      with_items: '{{ system_install_partitions }}'
