---

- include: harddrive.yml

- include: bootstrap.yml
  when:
    system_install_base is not defined
      or system_install_base == omit
      or system_install_base == ''

- include: base.yml
  when:
    system_install_base is defined
    and system_install_base != omit
    and system_install_base != ''


# Pseudo filesystems are required for grub operations and some package
# installations.
#
# TODO: explain why ansible mount cannot be used.
- name: mount pseudo file systems
  command:
    mount -o bind '{{ item.fs }}' '{{ system_install_target }}/{{ item.fs }}'
  args:
    creates: '{{ system_install_target }}/{{ item.fs }}/{{ item.creates }}'
    warn: false
  with_items: '{{ system_install_pseudo_fs }}'

- include: resolvconf.yml
  
- include: grub.yml    

- include: post-install.yml

- include: root-access.yml

