---

- include: harddrive.yml

- include: bootstrap.yml
  when:
    system_install_base is not defined
      or system_install_base == omit
      or system_install_base == ''

- include: base.yml
  when:
    system_install_base is defined
    and system_install_base != omit
    and system_install_base != ''


# Pseudo filesystems are required for grub operations and some package
# installations.
#
# TODO: explain why ansible mount cannot be used.
- name: mount pseudo file systems
  command:
    mount -o bind '{{ item.fs }}' '{{ system_install_target }}/{{ item.fs }}'
  args:
    creates: '{{ system_install_target }}/{{ item.fs }}/{{ item.creates }}'
    warn: false
  with_items: '{{ system_install_pseudo_fs }}'

# Allows name resolving in the chroot environment. This is only required for
# operations in the chroot.
- name: ensure /run/resolvconf exists
  file:
    path: /run/resolvconf
    state: directory

- name: copy /etc/resolv.conf to /run/resolvconf
  copy:
    src: /etc/resolv.conf
    dest: /run/resolvconf
    remote_src: yes

# Copy 
- name: copy /etc/resolv.conf to chroot
  copy:
    src: /etc/resolv.conf
    dest: '{{ system_install_target }}/etc/resolv.conf'
    remote_src: yes
  when: system_install_vendor in [ 'centos', 'arch' ]

    
- include: grub.yml    

- include: post-install-fix.yml

- include: root-access.yml

