
# Ensure fstab is set correctly to allow system boot.
- name: Setup fstab in chroot
  mount:
    src: '{{ system_install_drive }}{{ item.number }}'
    path: '{{ item.mount.path }}'
    fstype: '{{ item.filesystem.fstype }}'
    fstab: '{{ system_install_target }}/etc/fstab'
    state: present
  when:
    item.mount is defined
    and item.filesystem is defined
  with_items: '{{ system_install_partitions }}'

- include_tasks: post-install-fix-debian.yml
  when: system_install_vendor in [ 'debian', 'ubuntu' ]

- include_tasks: post-install-fix-centos.yml
  when: system_install_vendor in [ 'centos', 'fedora' ]

- include_tasks: post-install-fix-opensuse.yml
  when: system_install_vendor == 'opensuse'

- include_tasks: post-install-fix-alpine.yml
  when: system_install_vendor == 'alpine'

## Dbus could not find its runtime directory.
#
# See
#  - https://bugzilla.redhat.com/show_bug.cgi?id=1568856
#  - https://unix.stackexchange.com/questions/523250/dbus-issues-unable-to-connect
- name: Fix NetworkManager link
  command:
    ln -s /run/dbus '{{ system_install_target }}/var/run/dbus'
  args:
    creates: '{{ system_install_target }}/var/run/dbus'
    warn: false
  when: system_install_vendor in [ 'centos', 'fedora', 'opensuse' ]
